<a traget="_blank" href="../img/Ikarus-Bandfoto-web.jpg"><img style="width:100%;" src="../img/Ikarus-Bandfoto-web-small.jpg"/></a>
<p>
	Der musikalische Organismus IKARUS kehrt nach Echo mit dem schillernden zweiten Album Chronosome zurück. Der Titel ist eine Wortspiel mit zwei Begriffen, die prägend für die Aufnahme waren: Chromosom (DNA, die als Molekularkomplex verpackt ist) und Chronos (die Personifikation der Zeit). Ramón Oliveras – der Schlagzeuger, Komponist und Leader der Band – verspürte früh einen starken Appetit auf musikalische Einflüsse unterschiedlicher Art und nennt z.B. Bartôk, Meshuggah, Flying Lotus und Craig Taborn im gleiche Satz als seine Inspirationen. Das Album erforscht die Idee dieser musikalischen Evolution. Diese braucht nämlich vor allem zwei Dinge: Zeit und starke Umwelteinflüsse – die DNA des Albums erscheint so als Dokument der Veränderungen, welche die musikalische Form aufnimmt.
</p>
<p>
	Die DNA ist auch der Code, der die Essenz einer Lebensform ausdrückt, festhält und eine formale Kontinuität über längere Zeit garantiert. Der charakteristische IKARUS Klang und der eigene Kompositionsstil war bereits auf dem Debutalbum Echo hörbar. Mit Chronosome haben wir nun die entwickelten Iterationen dieses ursprünglichen Bauplanes vor uns, also die zweite Gen-Generation. IKARUS kombinieren immer noch verspielt abstrakte Formen mit komplexen Rhythmen und herausfordernden Taktarten. Aber neu klingt alles weniger ambitiös und darum runder. Das Stück Ontake ist durch einem 4/4 Puls geerdet, während das Schlagzeug einen 19/8 über einen 6/8 Loop spielt, das Piano einen 5/8 wiederholt und die Sänger darüber im 13/8 schweben. Das Stück klingt aber auch ohne dieses Wissen zugänglich und betörend, weil die Band stets ihre sinnliche Leichtigkeit behält.
</p>
<p>
Abgesehen von dem subtilen Zusammenspiel, der kompakten Produktion, und der musikalischen Beweglichkeit, welche die fünf Musiker durch die vielen Konzerte als Working-Band gewonnen haben, ist vor allem ein musikalischer Parameter neu sehr bemerkenswert: Klang-Farbe. Das Album ist voller schillernder, resonierender Farbenpracht. Es hört sich an, als ob man in einen Klang-Urwald aus leuchtenden und vibrierenden Farben und Formen tritt. Der Schritt von Echo zu Chronosome ist vergleichbar mit dem Wechsel im Kino von Schwarz-Weiss zu farbigem Film. Für Kenner des ersten Albums scheint Vieles vertraut, wirkt aber nun lebendiger und sinnlicher. Durch diesen Wandel fühlt sich Chronosome warm und natürlich an - nicht zuletzt wegen gelegentlich eigenartig samba-esquen Rhythmen. Die dunklen Töne des Vorgängers sind noch immer hörbar, aber sie dienen nun mehr als Hintergrund um die Tiefenschärfe der neuen Klangfarben zu verstärken. Mit diesem dualistischen Spiel kreiert IKARUS eine wundervoll paradoxe Spannung zwischen Wintermelancholie und einem Tag in Rio.
</p>
