
		<p> <b>Ramón Oliveras</b> schloss 2014 seinen Master of Arts in Music an der Zürcher Hochschule der Künste ab. Schwerpunkt seines musikalischen Schaffens bildet das Projekt IKARUS, eine Formation, die Jazzmusik als Gesamtkunstwerk inszeniert. Er ist ausserdem Co-Leader des internationalen Trios Punkt3, Schlagzeuger und Manager des Soulsängers Bee Johnson, sowie Komponist der modernen Oper GENESIS – Alive. Ramón wird von der Friedl Wald Stiftung und der Hirschmann Stiftung unterstützt. Zusammen mit Andreas Lareida und Manuel Pasquinelli leitet er das Musikerlabel Morpheus-Records. Als Schlagzeuger arbeitete er u.A. in Projekten mit Chris Wiesendanger, Christoph Grab, Yves Theiler, Patrice Moret und Tobias Meier.</p>

		<p> <b>Stefanie Suhner</b> schloss 2013 mit dem Master of Arts in Jazzgesang an der Zürcher Hochschule der Künste ab und lebt in Zürich. Unter anderem ist Stefanie Backing Vocalist beim Schweizer Soulsänger Seven und Sopranistin von The Voices, mit welchem sie sowohl auf der letzten Pepe Lienhard Tournee dabei war, als auch auf Udo Jürgens’ der ganz normale Wahnsinn-Tournee 2012 und 2013. Ihre eigene Band Amelié Junes feierte im Mai 2013 Premiere. Stefanie hat u.A. bei Marianne Racine, Rahel Hadorn, Chris Wiesendanger und Lisette Spinnler studiert und Masterclasses von Maria Schneider, Gretchen Parlato, Aaron Goldberg uvm. besucht. </p>

		<p> <b>Andreas Lareida</b> hat an der Hochschule der Künste Bern HKB Jazzgesang studiert und 2011 mit dem Master of Arts in Music Performance abgeschlossen. Sein Ensemble Àgora hat soeben seine erste CD Veröffentlichung hinter sich. Er fühlt sich im Jazz, wie auch in der freier Improvisation und dem Pop zuhause. Er ist Organisator der Reihe Kind of Jazz, welche Konzerte in Luzern und Bern veranstalten, sowie Tätig für das Musikerlabel Morpheus Records. Als Musiker arbeitete er u.A. mit Sandy Patton, Colin Vallon, Patrice Moret, Andreas Schaerer, Franics Coletta und Django Bates. </p>

		<p> <b>Lucca Fries</b> hat schon während seines Studiums an der Hochschule Luzern - Musik, welches er 2012 mit einem Master in Jazz Performance abgeschlossen hat, mit seinem authentischen und intensiven Spiel auf sich aufmerksam gemacht. Heute hört man ihn vor allem mit seiner Band Hely mit dem Zürcher Schlagzeuger Jonas Ruther, wovon 2013 das Debutalbum erschien. Er tritt regelmässig als Solopianist auf und spielt mit dem Luzerner Saxofonisten Noah Arnold in verschiedenen Formationen. Lucca Fries lebt in Winterthur.</p>

		<p> <b>Moritz Meyer</b> ist als vielseitiger und aktiver Bassist der jungen Jazzgeneration bekannt und lebt in Zürich. Neben verschiedenen Jazzformationen fühlt er sich auch im Pop zuhause. Er ist dort als Mitglied der Band Liv Summer, What Josephin Saw und Cecilia Hunch aktiv. Seit einem Jahr pendelt er zwischen Zürich und London, und versucht dort ein zweites Standbein als Musiker aufzubauen. </p>

