<p> <b>Ramón Oliveras</b> ist Schlagzeuger und Komponist und lebt in Zürich und Berlin. Er schloss 2014 den Master of Arts in Schlagzeug an der Zürcher Hochschule der Künste ab und studierte von 2016-2017 zeitgenössische Komposition ebenfalls an der ZHdK. In seinen eigenen Projekten Ikarus und JPTR lebt er seine musikalische Sprache und seine Vision von Musik als Gesamtkunstwerk. Ramón spielt zudem Schlagzeug im internationalen Trio Punk3 und ist Mitorganisator und Booker beim Perlaton Festival. Stipendien und Förderbeiträge: 2017 Composer Exchange Liszt-institute Budapest, 2017 Residency Medelina Curraglia, 2016 Residency Re/Fugium Dangio-Torre, 2015 Residency Maison des Artistes,  2013 Förderpreis der Friedl-Wald-Stiftung, 2013 Hirschmann-Stipendium.</p>

<p> <b>Anna Hirsch</b> schloss 2015 den Bachelor Gesang an der Hochschule für Musik Basel ab. Neben ihrem eigenen Projekt Hila Puntur, ist sie Teil des Duos FLEEB, des Impro-Kollektivs um Kaspar von Grünigen, sowie des Trios Go Ask Alice. Sie ist zudem Mitorganisatorin der Konzertreihe „Laboratorium für frei improvisierte Musik“, Mitbegründerin des Basler Labels Hout Records und erhielt 2015 den Förderpreis der Friedl Wald Stiftung. Sie lebt in Basel.</p>

<p> <b>Andreas Lareida</b> hat an der Hochschule der Künste Bern HKB Gesang studiert und 2011 mit dem Master of Arts in Music Performance abgeschlossen. Sein Ensemble Àgora arbeitet im Moment am zweiten Album. Er ist zudem Teil der künstlerischen Leitung des Tanzensembles Éolienne Danse und ist regelmässig im Theater Rigiblick bei Musiktheatern auf der Bühne.</p>

<p> <b>Lucca Fries</b> schloss 2012 seinen Master of Arts in Music Performance in Luzern ab. Neben Ikarus hört man ihn vor allem mit seiner Band Hely (mit Jonas Ruther), deren zweites Album Jangal im 2016 auf Traumton Records erschien und mit dem sie in Indien auf Festivaltour waren. Mit ihrem Debutalbum „Rapture“ wurden sie für die Swiss Diagonal Jazz Tour 2015 ausgewählt. Lucca Fries lebt in Winterthur.</p>

<p> <b>Moritz Meyer</b> ist als aktiver Kontrabassist bekannt und lebt in Zürich. Neben Ikarus und dem Joscha Schraff Quartett hat er auch als Mitglied von Cilia Hunch mehrere Alben aufgenommen und ist auf diversen Bühnen anzutreffen.</p>
