
		<p> <b>Ramón Oliveras</b> schloss 2014 mit dem Master of Arts in Jazzschlagzeug an der Zürcher Hoch- schule der Künste ab. Er lebt in seinen eigenen Projekten IKARUS und dem Duo JPTR seine mu- sikalische Sprache und seine Vision von Musik als Gesamtkunstwerk. Ramón ist zudem Schlagzeuger im internationalen Trio Punkt3. Er ist Booker beim Zürcher Festival Perlaton und lebt in Zürich. Stipendien und Förderbeiträge: 2016 Artist in Residency: Re/fugium, 2016 Artist in Residency: Maison des Artist, 2013 Förderpreis der Friedl-Wald-Stiftung, 2013 Hirschmann-Stipendium</p>

		<p> <b>Stefanie Suhner</b> schloss 2013 mit dem Master of Arts in Jazzgesang an der Zürcher Hochschule der Künste ab und lebt in Zürich. Unter anderem ist Stefanie Backing Vocalist beim Schweizer Soul- sänger Seven und Sopranistin von The Voices, mit welchen sie auf Udo Jürgens’ der ganz normale Wahnsinn-Tournee 2012 bis 2014. Ihr Soloprojekt Amelié Junes veröffentlichte soeben das erstes Al- bum produziert von James Gruntz. </p>

		<p> <b>Andreas Lareida</b> hat an der Hochschule der Künste Bern HKB Jazzgesang studiert und 2011 mit dem Master in Music Performance abgeschlos- sen. Sein Ensemble Àgora arbeitet im Moment am zweiten Album. Er fühlt sich im Jazz, wie auch in der freier Improvisation und dem Pop zuhause und ist Organisator der Reihe Kind of Jazz, welche Kon- zerte in Luzern und Bern veranstalten. </p>

		<p> <b>Lucca Fries</b> schloss 2012 seinen Master of Arts in Music Performance in Luzern ab. Man hört ihn neben Ikarus vor allem Solo oder mit seiner Band Hely mit dem Zürcher Schlagzeuger Jonas Ruther, wovon gerade das zweite Album erscheinte. Ihr Debutalbum „Rapture“ wurde für die Swiss Diago- nal Jazz Tour 2015 ausgewählt. Lucca Fries lebt in Winterthur.</p>

		<p> <b>Moritz Meyer</b> ist als vielseitiger und aktiver Bassist der jungen Musikergeneration bekannt und lebt in Zürich. Neben Ikarus und dem Joscha Schraff Quartett fühlt er sich vor allem im Pop zu- hause. Er ist dort als Mitglied der Band JAS CRW und Celia Hunch aktiv. Zurzeit pendelt er zwischen Zürich und London. </p>
