<p> <b>Ramón Oliveras</b> is a drummer and composer and lives in Zurich and Berlin. In 2014, he finished his master of arts in jazz drumming at the Zurich University of Arts and studied contemporary classical composition from 2016 to 2017 at ZHdK. He focuses on his own bands IKARUS and JPTR, in which he persues his very own musical language. Furthermore, Ramón plays the drums in the international trio Punkt3, is co-organiser and booker of the Perlaton Music Festival and writes contemporary classical music. Scholarships and prizes: 2017 Composer exchange Listz-Institut Budapest, 2017 Residency Medelina Curraglia 2016 Residency Re/Fugium Dangio-Torre, 2015 Residency Maison des Artistes Chamonix, 2013 Prize of the Foundation Friedl-Wald, 2013 Hirschmann Scholarship.</p>

<p> <b>Anna Hirsch</b> graduated in 2015 from Basel University of Arts with a master in jazz vocals and lives in Basel. She sings in her own project Hila Puntur and is a member of the duo FLEEB, Kaspar Grünigen’s impro collective and trio Go Ask Alice. Furthermore, she is co-organizer of the concert series “Laboratorium für frei improvisierte Musik”, co-founder of the basel label Hout Records and won the prize of the Foundation Friedl-Wald in 2015.</p>

<p> <b>Andreas Lareida</b> graduated in 2011 from Bern University of Arts with a master in jazz vocals and lives in Bern. His ensemble Àgora is working on theirw second album. He is the artistic director of the dance ensemble Élionne Danse and a regular on the music theater stage of Theater Rigiblick.</p>

<p> <b>Lucca Fries</b> graduated in 2012 from Lucerne University of Arts with a master in jazz piano and lives in Winterthur. Apart from Ikarus, he mainly works with his Duo Hely, of whom the second album Jangal was released in April 2016 on Traumton Records and with which they played a festival tour in India. Their first album Rapture earned them a spot at the Swiss Diagonal Jazz tour in 2015.</p>

<p> <b>Moritz Meyer</b> graduated in 2013 from Zurich University of Arts with a master in jazz bass and lives in Zurich and London. Apart from Ikarus und the Joscha Schraff Quartet, he recorded albums with Celia Hunch and plays many different stages.</p>
